from .about_us import AboutUs
from .coll_back import CollBack
from .documentation import Documentation
from .faq import Faq
from .home import HomePageText
from .main_comments import MainComments
from .main_slider import MainSlider
from .order import Order
from .partners import Partners
