# Generated by Django 2.1.5 on 2019-02-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('image',), 'verbose_name': 'Общая галлерея изображений для портфолио', 'verbose_name_plural': '1. Общая галлерея изображений для портфолио'},
        ),
        migrations.AlterModelOptions(
            name='portfolio',
            options={'ordering': ('name',), 'verbose_name': 'Портфолио', 'verbose_name_plural': '3. Объекты портфолио'},
        ),
        migrations.AlterModelOptions(
            name='topic',
            options={'verbose_name': 'Категории раздела портфолио', 'verbose_name_plural': '2. Категории раздела портфолио'},
        ),
    ]
