# Generated by Django 2.1.5 on 2019-02-18 01:00

import ckeditor_uploader.fields
from django.db import migrations, models
import others.models.partners
import others.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutUs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_about_us_page', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текс на странице о нас 1 часть')),
                ('text_about_us_page_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текс на странице контакты')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон компании')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес компании')),
                ('time_work', models.CharField(blank=True, max_length=200, null=True, verbose_name='Время работы компании')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании')),
                ('smal_company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сокрощенное наименование компании')),
                ('discription_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание навания на главную')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Примечания, в футере')),
                ('full_company_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Полное наименование компании')),
                ('fio_entrepreneur', models.CharField(blank=True, max_length=200, null=True, verbose_name='ФИО предпринимателя')),
                ('ip_registration_address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес регистрации ИП')),
                ('inn_kpp', models.CharField(blank=True, max_length=200, null=True, verbose_name='ИНН')),
                ('bin', models.CharField(blank=True, max_length=200, null=True, verbose_name='ОГРНИП')),
                ('okved', models.CharField(blank=True, max_length=200, null=True, verbose_name='ОКВЭД')),
                ('okpo', models.CharField(blank=True, max_length=200, null=True, verbose_name='ОКПО')),
                ('requisites', models.TextField(blank=True, null=True, verbose_name='Банковские реквизиты')),
                ('self_phone', models.CharField(blank=True, max_length=200, null=True, verbose_name='Контактный телефон')),
                ('self_email', models.CharField(blank=True, max_length=200, null=True, verbose_name='Электронная почта')),
            ],
            options={
                'verbose_name': 'Тексты страницы о компании и контакты',
                'verbose_name_plural': 'Тексты страницы о компании и контакты',
            },
        ),
        migrations.CreateModel(
            name='CollBack',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=200, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=500, null=True, verbose_name='Описание')),
                ('description_short', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание короткое')),
                ('btn_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя кнопки')),
                ('image', models.ImageField(blank=True, null=True, upload_to='coll_back', verbose_name='Изображение')),
                ('avalible', models.BooleanField(default=True, verbose_name='Доступность обратного звонка')),
            ],
            options={
                'verbose_name': 'Настройки страницы заказа обратного звонка',
                'verbose_name_plural': 'Настройки страницы заказа обратного звонка',
            },
        ),
        migrations.CreateModel(
            name='CollBackClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_client', models.CharField(max_length=100, verbose_name='Телефон клиента')),
                ('coll_time', models.CharField(max_length=300, verbose_name='Время обратного звонка')),
                ('description_client', models.TextField(blank=True, null=True, verbose_name='Описание клиента')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказ клиента на звонок',
                'verbose_name_plural': 'Заказ клиента на звонок',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Documentation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('file', models.FileField(upload_to='documentation', validators=[others.validators.validate_file_extension], verbose_name='Файл')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Документация',
                'verbose_name_plural': 'Документация',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Faq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=400, verbose_name='Вопрос')),
                ('answer', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Ответ на вопрос')),
            ],
            options={
                'verbose_name': 'FAQ/Часто задоваемые вопросы',
                'verbose_name_plural': 'FAQ/Часто задоваемые вопросы',
            },
        ),
        migrations.CreateModel(
            name='HomePageText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_home_page', ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текс на главной странице')),
                ('text_home_page_2', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текс на главной странице 2 часть')),
            ],
            options={
                'verbose_name': 'Тексты главной страницы',
                'verbose_name_plural': 'Тексты главной страницы',
            },
        ),
        migrations.CreateModel(
            name='MainComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_person', models.CharField(max_length=200, verbose_name='Имя того кто написал отзыв')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=100, null=True, verbose_name='Телефон')),
                ('job_satisfaction', models.IntegerField(verbose_name='Оценка')),
                ('kind_job', models.CharField(blank=True, max_length=200, null=True, verbose_name='Какие работы производились')),
                ('comment_body', models.TextField(blank=True, null=True, verbose_name='Тело коментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'verbose_name_plural': 'Отзывы',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='MainSlider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=50, null=True, verbose_name='Заголовок')),
                ('description', models.CharField(blank=True, max_length=200, null=True, verbose_name='Описание')),
                ('image', models.ImageField(upload_to='main_slider', verbose_name='Изображение слайда')),
                ('button_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кнопки')),
                ('serial_number', models.PositiveIntegerField(default=1, verbose_name='Порядковый номер слайда')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Слайдер на главной странице',
                'verbose_name_plural': 'Слайдер на главной странице',
                'ordering': ('serial_number',),
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_client', models.CharField(max_length=200, verbose_name='Имя клиента')),
                ('phone_client', models.CharField(max_length=100, verbose_name='Телефон клиента')),
                ('email_client', models.EmailField(max_length=254, verbose_name='Email')),
                ('subject_work', models.CharField(max_length=200, verbose_name='Тематика работ')),
                ('description_client', models.TextField(blank=True, null=True, verbose_name='Описание заказа клиента')),
                ('file', models.FileField(blank=True, null=True, upload_to='order_file', validators=[others.validators.validate_file_extension], verbose_name='Файл клиента')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Заказы клиентов',
                'verbose_name_plural': 'Заказы клиентов',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Partners',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя партнера или бренды')),
                ('image', models.ImageField(upload_to=others.models.partners.generate_filename, verbose_name='Изобраение')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Сыллка если есть')),
            ],
            options={
                'verbose_name': 'Партнеры и бренды',
                'verbose_name_plural': 'Партнеры и бренды',
            },
        ),
    ]
