# Generated by Django 2.1.5 on 2019-02-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0002_auto_20190224_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='aboutus',
            options={'verbose_name': 'Тексты страницы о компании и контакты (только одна модель)', 'verbose_name_plural': 'Тексты страницы о компании и контакты (только одна модель)'},
        ),
        migrations.AlterModelOptions(
            name='collback',
            options={'verbose_name': 'Настройки страницы заказа обратного звонка (только одна модель)', 'verbose_name_plural': 'Настройки страницы заказа обратного звонка (только одна модель)'},
        ),
        migrations.AlterModelOptions(
            name='homepagetext',
            options={'verbose_name': 'Тексты главной страницы (только одна модель)', 'verbose_name_plural': 'Тексты главной страницы (только одна модель)'},
        ),
    ]
