# Generated by Django 2.1.5 on 2019-02-25 18:06

import ckeditor_uploader.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0003_auto_20190225_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutus',
            name='address',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес компании (отображается в шапке сайта)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='discription_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Описание навания на главную (отображается под сокращенным назаванием компании)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email компании (отображается в шапке сайта)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='phone',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Телефон компании (отображается в шапке сайта)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='smal_company_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Сокрощенное наименование компании (отображается в шапке сайта)'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_about_us_page',
            field=ckeditor_uploader.fields.RichTextUploadingField(verbose_name='Текс на странице "О нас"'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='text_about_us_page_2',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Текс на странице "Контакты"'),
        ),
        migrations.AlterField(
            model_name='aboutus',
            name='time_work',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Время работы компании (отображается в низу сайта и странице "Контакты")'),
        ),
    ]
