# Generated by Django 2.1.5 on 2019-03-02 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0004_auto_20190225_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='mainslider',
            name='button_name_coll_back',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название кнопки обратного звонка'),
        ),
    ]
