# Generated by Django 2.1.5 on 2019-03-03 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('others', '0005_mainslider_button_name_coll_back'),
    ]

    operations = [
        migrations.AddField(
            model_name='aboutus',
            name='title_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Заголовок примечаний, в футере'),
        ),
    ]
