# Generated by Django 2.1.5 on 2019-02-25 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_some_settings', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sitesettings',
            options={'verbose_name': 'Настройки сайта (только одна модель)', 'verbose_name_plural': 'Настройки сайта (только одна модель)'},
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email на которые будут приходить оповещения'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_new_coll_back_order',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новой заявке на обратный звонок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_new_main_comment',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новых отзывах'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_new_order',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новом заказе'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_new_portfolio_comments',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новых коментариях в разделе "портфолио"'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='alert_new_services_comments',
            field=models.BooleanField(default=True, verbose_name='Оповещать о новых коментариях в разделе "предоставляемые услуги"'),
        ),
    ]
