# Generated by Django 2.1.5 on 2019-02-28 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_some_settings', '0002_auto_20190225_1727'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='mail_message_comment_create',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения оправляемого клиенту при успешном добавление коментария'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_message_footer',
            field=models.TextField(blank=True, null=True, verbose_name='Текст в низу сообщения (пожелания, с уважением)'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_message_order_create',
            field=models.TextField(blank=True, null=True, verbose_name='Текст сообщения оправляемого клиенту при успешном оформлении им заказа'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_subject_comment_create',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст темы сообщения оправляемого клиенту при успешном добавлении какого либо коментария или отзыва'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='mail_subject_order_create',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Текст темы сообщения оправляемого клиенту при успешном оформлении им заказа'),
        ),
    ]
