# Generated by Django 2.1.5 on 2019-03-03 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('site_some_settings', '0003_auto_20190228_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitesettings',
            name='name_bottom_coll_back',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке оформления заказа на обратный звонок'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='name_bottom_order',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Текст на кнопке оформления заказа'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Название сайта отображается в название вкладки'),
        ),
    ]
