# Generated by Django 2.1.5 on 2019-02-18 01:00

import ckeditor_uploader.fields
from django.db import migrations, models
import django.db.models.deletion
import service.models.images
import service.models.kindworks
import service.models.service


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=service.models.images.generate_filename, verbose_name='Все изображения приложения услуги')),
                ('name', models.CharField(max_length=200, unique=True, verbose_name='Наименование')),
                ('description', models.CharField(blank=True, max_length=800, null=True, verbose_name='Описаниее')),
                ('slug', models.SlugField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
            ],
            options={
                'verbose_name': 'Изображения',
                'verbose_name_plural': 'Изображения',
                'ordering': ('image',),
            },
        ),
        migrations.CreateModel(
            name='KindWorks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Тематика работ')),
                ('slug', models.SlugField()),
                ('intro', models.CharField(blank=True, max_length=200, null=True, verbose_name='Краткое описание')),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=service.models.kindworks.generate_filename, verbose_name='Главное изображение')),
                ('desctiption', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание производимы работ')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('gallery_availability', models.BooleanField(default=False, verbose_name='Отобраать галлерею изображений в конце страницы')),
                ('image', models.ManyToManyField(blank=True, to='service.Images', verbose_name='Галерея изображений отображаемая в низу')),
            ],
            options={
                'verbose_name': 'Тематика работ',
                'verbose_name_plural': 'Тематика работ',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='KindWorksComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_object', models.IntegerField(blank=True, null=True, verbose_name='ID Объектa коментирования')),
                ('name_person', models.CharField(max_length=200, verbose_name='Имя того кто написал коментарий')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('comment_body', models.TextField(verbose_name='Тело коментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Коментарии объектов "типы работ"',
                'verbose_name_plural': 'Коментарии объектов "типы работ"',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Наименование работ')),
                ('slug', models.SlugField(unique=True)),
                ('main_image', models.ImageField(blank=True, null=True, upload_to=service.models.service.generate_filename, verbose_name='Главное изображение')),
                ('desctiptions', ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('price', models.CharField(blank=True, max_length=50, null=True, verbose_name='Цена за 1 ед. измер')),
                ('gallery_availability', models.BooleanField(default=True, verbose_name='Отобраать галлерею изображений в конце страницы')),
                ('image', models.ManyToManyField(blank=True, to='service.Images', verbose_name='Галерея изображений отобрааемая в низу')),
                ('kindworks', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='service.KindWorks', verbose_name='Отношение к тематике работ')),
            ],
            options={
                'verbose_name': 'Наименование работ',
                'verbose_name_plural': 'Предоставлямемые услуги',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='ServiceComments',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_object', models.IntegerField(blank=True, null=True, verbose_name='ID Объектa коментирования')),
                ('name_person', models.CharField(max_length=200, verbose_name='Имя того кто написал коментарий')),
                ('email', models.CharField(max_length=200, verbose_name='Email')),
                ('comment_body', models.TextField(verbose_name='Тело коментария')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Обновлен')),
                ('moderation', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Коментарии объектов объектов "предоставяемые услуги"',
                'verbose_name_plural': 'Коментарии объектов объектов "предоставяемые услуги"',
                'ordering': ('-updated',),
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
                'ordering': ('name',),
            },
        ),
        migrations.AddField(
            model_name='service',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='service.Unit', verbose_name='Единица измерения'),
        ),
        migrations.AlterIndexTogether(
            name='images',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='service',
            index_together={('id', 'slug')},
        ),
        migrations.AlterIndexTogether(
            name='kindworks',
            index_together={('id', 'slug')},
        ),
    ]
