# Generated by Django 2.1.5 on 2019-02-25 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0002_auto_20190224_0635'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ('image',), 'verbose_name': 'Галлерея для всего раздела услуг', 'verbose_name_plural': '1. Галлерея для всего раздела услуг'},
        ),
        migrations.AlterModelOptions(
            name='kindworks',
            options={'ordering': ('name',), 'verbose_name': 'Тематика работ', 'verbose_name_plural': '2. Тематика работ'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'ordering': ('name',), 'verbose_name': 'Наименование работ (подкласс тематики работ)', 'verbose_name_plural': '3. Предоставлямемые услуги (подкласс тематики работ)'},
        ),
    ]
